set(AVR_TOOLCHAIN_PATH /opt/AVR_Tool_Chain/avr8-gnu-toolchain-linux_x86_64)
set(CMAKE_C_COMPILER /opt/AVR_Tool_Chain/avr8-gnu-toolchain-linux_x86_64/bin/avr-gcc )
set(CMAKE_CXX_COMPILER /opt/AVR_Tool_Chain/avr8-gnu-toolchain-linux_x86_64/bin/avr-g++)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR "avr")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
